### ISSUE TITLE
flowsteps 接口在有state或transaction删除后不能正常返回， 可否将已关闭或已完成的工单做一个快照。

### ISSUE THREAD

**Issue by luozhijunroy18** [blackholll/loonflow#304]
## ISSUE TEMPLATE

使用的版本:r2.0.6

问题详细描述:
flowsteps 接口在有state或transaction删除后不能正常返回， 可否将已关闭或已完成的工单做一个快照。

是否查看了系统日志(默认在启动用户家目录下loonflow.log):
2021-09-22 18:17:20,144 /opt/loonflow/service/common/log_service.py process-25 thread-140135058372672 20 [ERROR]: Traceback (most recent call last):
  File "/opt/loonflow/service/common/log_service.py", line 17, in _deco
    real_func = func(*args, **kwargs)
  File "/opt/loonflow/service/ticket/ticket_base_service.py", line 1624, in get_flow_log_transition_name
    transition_name = transition_obj.name
AttributeError: 'NoneType' object has no attribute 'name'

应该是找不到对应的动作了， 因为我删除过一些动作（transition）
是否搜索过历史issue:

做过哪些尝试:

**Comment by blackholll** [comment]
两种方案：
1.工作流支持多版本， 每个工单创建后对应的工作流信息就固定了。 flowstep接口从工单对应的工作流信息中获取
2.针对不存在state或transition，做兼容处理，返回“未知状态”或“未知操作”

方案2 下个小版本我优化支持下、方案1改动较大，短期内不会支持

**Comment by blackholll** [comment]
optimize in https://github.com/blackholll/loonflow/releases/tag/r2.0.7
