### ISSUE TITLE
使用python manage.py migrate初始化数据库时出现错误

### ISSUE THREAD

**Issue by wayne-mao** [blackholll/loonflow#374]
## ISSUE TEMPLATE

使用的版本:
2.0.13
问题详细描述:
使用python manage.py migrate初始化数据库时出现错误
错误信息如下：
`
  Applying sessions.0001_initial... OK
  Applying ticket.0001_initial...Traceback (most recent call last):
  File "/home/Wayne/anaconda3/envs/backend/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/home/Wayne/anaconda3/envs/backend/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/Wayne/anaconda3/envs/backend/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/Wayne/anaconda3/envs/backend/lib/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/Wayne/anaconda3/envs/backend/lib/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1118, 'Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/home/Wayne/anaconda3/envs/backend/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/Wayne/anaconda3/envs/backend/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/Wayne/anaconda3/envs/backend/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/Wayne/anaconda3/envs/backend/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/Wayne/anaconda3/envs/backend/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/Wayne/anaconda3/envs/backend/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/home/Wayne/anaconda3/envs/backend/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/Wayne/anaconda3/envs/backend/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/Wayne/anaconda3/envs/backend/lib/python3.6/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/Wayne/anaconda3/envs/backend/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/Wayne/anaconda3/envs/backend/lib/python3.6/site-packages/django/db/migrations/operations/models.py", line 92, in database_forwards
    schema_editor.create_model(model)
  File "/home/Wayne/anaconda3/envs/backend/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 307, in create_model
    self.execute(sql, params or None)
  File "/home/Wayne/anaconda3/envs/backend/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/home/Wayne/anaconda3/envs/backend/lib/python3.6/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/Wayne/anaconda3/envs/backend/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/Wayne/anaconda3/envs/backend/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/Wayne/anaconda3/envs/backend/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/Wayne/anaconda3/envs/backend/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/Wayne/anaconda3/envs/backend/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/home/Wayne/anaconda3/envs/backend/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/Wayne/anaconda3/envs/backend/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/Wayne/anaconda3/envs/backend/lib/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/Wayne/anaconda3/envs/backend/lib/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1118, 'Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs')
`
是否查看了系统日志(默认在启动用户家目录下loonflow.log):
系统日志为空
是否搜索过历史issue:
看了全部，没找到类似的
做过哪些尝试:
系统库更新了mysqlclient到2.0.3

**Comment by blackholll** [comment]
猜测是apps.models.TicketFlowLog中字段的问题，吧suggestion的类型改成text试下

**Comment by blackholll** [comment]
row size too large是表中出blob和text类型字段后 其他字段之和*N不可以超过65535， 然后根据字符集的不同，这个N会不同，大概是utfmb4这里的N会是3。然后TicketFlowLog中有两个长度是10000的， 可能会导致超出。 初步来看原因在这个。
这几天有点忙，晚点本地复现后详细看下

**Comment by wgf4242** [comment]
ticket_data 我改成TextField能通过。

**Comment by blackholll** [comment]
fixed in https://github.com/blackholll/loonflow/releases/tag/r2.0.14
