### ISSUE TITLE
2.0.13 dev 无法登录

### ISSUE THREAD

**Issue by simonzhang98** [blackholll/loonflow#375]
## ISSUE TEMPLATE

使用的版本:  2.0.13

问题详细描述:  dev 版本无法登陆

是否查看了系统日志(默认在启动用户家目录下loonflow.log):   查了 日志，报错如下

2022-05-24 16:48:54,367 C:\Program Files\Python38\lib\site-packages\django\utils\log.py process-3808 thread-5052 241 [ERROR]: Internal Server Error: /api/v1.0/login
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Program Files\Python38\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\Python38\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\temp\loonflow-master\apps\loon_base_view.py", line 31, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\temp\loonflow-master\apps\account\views.py", line 571, in post
    return api_response(0, '', {'jwt': jwt_info.decode('utf-8')})
AttributeError: 'str' object has no attribute 'decode'

将 571 行如下修改后问题解决
 return api_response(0, '', {'jwt': jwt_info})

**Comment by simonzhang98** [comment]
经查，是由于PyJWT和JWT同时存在，导入jwt模块时出现混淆, 卸载JWT包后，不用修改代码也可以登录

**Comment by simonzhang98** [comment]
原来是 PyJWT 版本导致的问题，1.7 版本返回的是 byte,  而 2.0 版本直接返回 str

**Comment by blackholll** [comment]
requirements/common.txt 中固定的pyjwt版本为1.7。 文档中(https://loonflow.readthedocs.io/)也有说明如何安装依赖  为何你会用2.0的版本
