### ISSUE TITLE
AttributeError: 'str' object has no attribute 'label'

### ISSUE THREAD

**Issue by quwquguoqing** [blackholll/loonflow#411]
## ISSUE TEMPLATE

使用的版本:2.0.12

问题详细描述: 修改了工作流的节点内容以及标书信息后出现报错

是否查看了系统日志(默认在启动用户家目录下loonflow.log):
2023-02-27 13:01:35,439 /opt/workflow/loonflow/service/common/log_service.py process-3583 thread-140309320951552 20 [ERROR]: Traceback (most recent call last):
  File "/opt/workflow/loonflow/service/common/log_service.py", line 17, in _deco
    real_func = func(*args, **kwargs)
  File "/opt/workflow/loonflow/service/ticket/ticket_base_service.py", line 224, in get_ticket_list
    state_label=json.loads(state_obj.label)),
AttributeError: 'str' object has no attribute 'label'

是否搜索过历史issue: 是

做过哪些尝试: 无法删除 所有工单中没有显示相关工单信息

**Comment by blackholll** [comment]
因为存在一些工单当前所处的状态被删除了，导致回去不到状态的信息。  你可以进管理员干预界面将工单强制关闭  或者升级到当前最新版本r2.0.15。  该已优化

**Comment by quwquguoqing** [comment]
ok，我升级下新版本！
