### ISSUE TITLE
close的工单查询报错

### ISSUE THREAD

**Issue by EFX1SZH** [blackholll/loonflow#425]
## ISSUE TEMPLATE

使用的版本:2.0.15

问题详细描述:close的工单查询报错

是否查看了系统日志(默认在启动用户家目录下loonflow.log):
2023-03-31 10:05:38,028 D:\codes\loonflow-new\service\common\log_service.py process-14504 thread-7932 20 [ERROR]: Traceback (most recent call last):
  File "D:\codes\loonflow-new\service\common\log_service.py", line 17, in _deco
    real_func = func(*args, **kwargs)
  File "D:\codes\loonflow-new\service\ticket\ticket_base_service.py", line 679, in get_ticket_detail
    display_form_field_list = json.loads(workflow_obj.display_form_str) if workflow_obj.display_form_str else []
  File "D:\OpCon\Bin\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\OpCon\Bin\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\OpCon\Bin\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 81 (char 80)

**Comment by blackholll** [comment]
工作流配置里面 工作流的展现表单属性里面的内容非json导致的，检查下此配置
