### ISSUE TITLE
审批邮件通知

### ISSUE THREAD

**Issue by wtxhai** [blackholll/loonflow#485]
## ISSUE TEMPLATE

使用的版本:V2.0.19

问题详细描述:当审批流流转到部门时，给对应的部门审批负责人发送邮件，邮件可以调用第三方，网易，office365等，这个目前有没有实现？

**Comment by blackholll** [comment]
添加一个通知， 配置一个通知hook.  在你的hook服务端实现发送邮件的逻辑。
工单状态发生变化的时候会触发hook.
hook demo： https://github.com/blackholll/loonflow_hook_demo/blob/main/loonflow_hook_demo/urls.py

**Comment by wtxhai** [comment]
这个工单的URL和TOKEN我在哪里获取？
![image](https://github.com/blackholll/loonflow/assets/49899065/f09aed59-2791-46c7-9f04-89f90eedf472)

**Comment by blackholll** [comment]
你需要参考  https://github.com/blackholll/loonflow_hook_demo/blob/main/loonflow_hook_demo/urls.py 自己写一个服务。 这个服务来实现具体发送邮件的逻辑。   自定义通知的时候填写的就是你的hook服务的地址。  
这里的token是为了你的hook服务校验请求来源的合法性，由你自己颁发， loonflow触发hook的时候会根据这个token来生成签名，放在header中，你的hook 根据token也生成签名来比对 保证请求是从loonflow发出的。   签名算法见  https://loonflow.readthedocs.io/zh-cn/r2.0.18/manage/workflow_config/?highlight=%E9%80%9A%E7%9F%A5#id2

**Comment by wtxhai** [comment]
在初始化状态下增加了hook，为啥没有被触发。
![image](https://github.com/blackholll/loonflow/assets/49899065/10c2e3bb-9989-42e9-b08f-71fbcc343079)
基础信息：
![image](https://github.com/blackholll/loonflow/assets/49899065/0eb9eeec-a1b7-41c9-a7bb-fe5d609f48e4)
hook配置：
![image](https://github.com/blackholll/loonflow/assets/49899065/7061be5d-1418-43ea-9327-f563d4c55722)
hook.view
`# hooks/views.py

from django.http import JsonResponse
from django.core.mail import send_mail
from django.views import View
from django.views.decorators.csrf import csrf_exempt
import json

@csrf_exempt
class EmailHookView(View):
    def post(self, request):
        data = json.loads(request.body.decode('utf-8'))  # 解析请求中的JSON数据
        work_order_id = data.get('order_number')
        new_status = data.get('new_status')

        print(work_order_id, new_status)

        # 发送邮件通知
        subject = f"工单 {work_order_id} 状态已变更为 {new_status}"
        message = f"工单 {work_order_id} 的状态已经变更为 {new_status}，请注意查看。"
        recipient_list = ['wtxhai@126.com']  # 邮件接收者列表

        send_mail(subject, message, 'netzsch_nlp@outlook.com', recipient_list)

        return JsonResponse({'message': 'Hook request handled successfully'})
`
hook.urls
`from django.urls import path

from apps.hook.views import EmailHookView

urlpatterns = [
    path('/hook_email', EmailHookView),
]`

**Comment by blackholll** [comment]
hook 依赖celery任务，celery进程是否有启动

**Comment by wtxhai** [comment]
启动的时候报错了：
[2024-06-05 11:44:59,213: WARNING/MainProcess] Message: 'Task handler raised error: %r'
Arguments: (ValueError('not enough values to unpack (expected 3, got 0)'),)

**Comment by blackholll** [comment]
信息给全点。  截个图 包括启动命令 出错的完整信息

**Comment by wtxhai** [comment]
启动成功了，好像执行hook的时候报错了
`PS D:\nlpflow> celery -A tasks worker -l info -Q loonflow
 
 -------------- celery@NLPM269 v5.2.7 (dawn-chorus)
--- ***** -----
-- ******* ---- Windows-10-10.0.19044-SP0 2024-06-05 11:49:26
- *** --- * ---
- ** ---------- [config]
- ** ---------- .> app:         loonflow:0x211f5875450
- ** ---------- .> transport:   redis://127.0.0.1:6379/0
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> loonflow         exchange=loonflow(direct) key=loonflow


[tasks]
  . tasks.debug_task
  . tasks.flow_hook_task
  . tasks.run_flow_task
  . tasks.send_ticket_notice
  . tasks.test_task
  . tasks.timer_transition

[2024-06-05 11:49:27,072: INFO/MainProcess] Connected to redis://127.0.0.1:6379/0
[2024-06-05 11:49:27,083: INFO/MainProcess] mingle: searching for neighbors
[2024-06-05 11:49:27,664: INFO/SpawnPoolWorker-2] child process 7200 calling self.run()
[2024-06-05 11:49:27,669: INFO/SpawnPoolWorker-4] child process 5388 calling self.run()
[2024-06-05 11:49:27,677: INFO/SpawnPoolWorker-1] child process 26552 calling self.run()
[2024-06-05 11:49:27,684: INFO/SpawnPoolWorker-3] child process 15564 calling self.run()
[2024-06-05 11:49:27,693: INFO/SpawnPoolWorker-5] child process 7096 calling self.run()
[2024-06-05 11:49:27,702: INFO/SpawnPoolWorker-8] child process 17984 calling self.run()
[2024-06-05 11:49:27,702: INFO/SpawnPoolWorker-7] child process 25972 calling self.run()
[2024-06-05 11:49:27,706: INFO/SpawnPoolWorker-6] child process 29860 calling self.run()
[2024-06-05 11:49:28,103: INFO/MainProcess] mingle: all alone
[2024-06-05 11:49:28,120: WARNING/MainProcess] D:\Python\Lib\site-packages\celery\fixups\django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2024-06-05 11:49:28,135: INFO/MainProcess] celery@NLPM269 ready.
[2024-06-05 11:50:47,065: INFO/MainProcess] Task tasks.send_ticket_notice[b47aacc9-8007-49a2-916f-0d929c83717c] received
[2024-06-05 11:50:47,076: WARNING/MainProcess] --- Logging error ---
[2024-06-05 11:50:47,078: WARNING/MainProcess] Traceback (most recent call last):
[2024-06-05 11:50:47,079: WARNING/MainProcess]   File "D:\Python\Lib\logging\__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
[2024-06-05 11:50:47,079: WARNING/MainProcess]   File "D:\Python\Lib\logging\__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
[2024-06-05 11:50:47,079: WARNING/MainProcess]   File "D:\Python\Lib\site-packages\celery\utils\log.py", line 146, in format
    msg = super().format(record)
          ^^^^^^^^^^^^^^^^^^^^^^
[2024-06-05 11:50:47,079: WARNING/MainProcess]   File "D:\Python\Lib\logging\__init__.py", line 695, in format
    record.exc_text = self.formatException(record.exc_info)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-06-05 11:50:47,079: WARNING/MainProcess]   File "D:\Python\Lib\site-packages\celery\utils\log.py", line 142, in formatException
    r = super().formatException(ei)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-06-05 11:50:47,080: WARNING/MainProcess]   File "D:\Python\Lib\logging\__init__.py", line 645, in formatException
    traceback.print_exception(ei[0], ei[1], tb, None, sio)
[2024-06-05 11:50:47,080: WARNING/MainProcess]   File "D:\Python\Lib\traceback.py", line 124, in print_exception
    te = TracebackException(type(value), value, tb, limit=limit, compact=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-06-05 11:50:47,080: WARNING/MainProcess]   File "D:\Python\Lib\traceback.py", line 728, in __init__
    self.stack = StackSummary._extract_from_extended_frame_gen(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-06-05 11:50:47,080: WARNING/MainProcess]   File "D:\Python\Lib\traceback.py", line 413, in _extract_from_extended_frame_gen
    for f, (lineno, end_lineno, colno, end_colno) in frame_gen:
[2024-06-05 11:50:47,080: WARNING/MainProcess]   File "D:\Python\Lib\traceback.py", line 350, in _walk_tb_with_full_positions
    positions = _get_code_position(tb.tb_frame.f_code, tb.tb_lasti)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-06-05 11:50:47,080: WARNING/MainProcess]   File "D:\Python\Lib\traceback.py", line 363, in _get_code_position
    positions_gen = code.co_positions()
                    ^^^^^^^^^^^^^^^^^
[2024-06-05 11:50:47,080: WARNING/MainProcess] AttributeError: '_Code' object has no attribute 'co_positions'
[2024-06-05 11:50:47,080: WARNING/MainProcess] Call stack:
[2024-06-05 11:50:47,082: WARNING/MainProcess]   File "D:\Python\Lib\threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
[2024-06-05 11:50:47,083: WARNING/MainProcess]   File "D:\Python\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
[2024-06-05 11:50:47,083: WARNING/MainProcess]   File "D:\Python\Lib\site-packages\billiard\pool.py", line 504, in run
    return self.body()
[2024-06-05 11:50:47,084: WARNING/MainProcess]   File "D:\Python\Lib\site-packages\billiard\pool.py", line 899, in body
    for _ in self._process_result(1.0):  # blocking
[2024-06-05 11:50:47,084: WARNING/MainProcess]   File "D:\Python\Lib\site-packages\billiard\pool.py", line 878, in _process_result
    on_state_change(task)
[2024-06-05 11:50:47,084: WARNING/MainProcess]   File "D:\Python\Lib\site-packages\billiard\pool.py", line 853, in on_state_change
    state_handlers[state](*args)
[2024-06-05 11:50:47,084: WARNING/MainProcess]   File "D:\Python\Lib\site-packages\billiard\pool.py", line 835, in on_ready
    item._set(i, obj)
[2024-06-05 11:50:47,084: WARNING/MainProcess]   File "D:\Python\Lib\site-packages\billiard\pool.py", line 1828, in _set
    self.safe_apply_callback(
[2024-06-05 11:50:47,084: WARNING/MainProcess]   File "D:\Python\Lib\site-packages\billiard\pool.py", line 1796, in safe_apply_callback
    fun(*args, **kwargs)
[2024-06-05 11:50:47,085: WARNING/MainProcess]   File "D:\Python\Lib\site-packages\celery\worker\request.py", line 596, in on_failure
    error('Task handler raised error: %r', exc,
[2024-06-05 11:50:47,085: WARNING/MainProcess] Message: 'Task handler raised error: %r'
Arguments: (ValueError('not enough values to unpack (expected 3, got 0)'),)
`

**Comment by blackholll** [comment]
celery 4以后不支持windows。 参考这个试试 stackoverflow.com/questions/45744992/celery-raises-valueerror-not-enough-values-to-unpack

**Comment by wtxhai** [comment]
这个是什么原因造成的？
`[2024-06-05 13:42:34,711: INFO/MainProcess] Task tasks.send_ticket_notice[7e49ef4c-ed09-484a-981a-57b10f127f26] received
[2024-06-05 13:42:35,071: INFO/MainProcess] Task tasks.send_ticket_notice[7e49ef4c-ed09-484a-981a-57b10f127f26] succeeded in 0.35999999998603016s: (False, 'hook host is not allowed, please contact the administrator to alter the configure')
`

**Comment by blackholll** [comment]
配置文件中有个配置 HOOK_HOST_ALLOWED

**Comment by wtxhai** [comment]
已经配置了，还是报错：
![image](https://github.com/blackholll/loonflow/assets/49899065/f7d3e22c-8954-41fa-914f-85c057ec189b)

**Comment by blackholll** [comment]
配置后 celery进程需要重启

**Comment by wtxhai** [comment]
![image](https://github.com/blackholll/loonflow/assets/49899065/e186ec8e-23f0-4448-89e2-765c0b6d34f3)
我把端口加进去了，这个应该是启动成功了。但是为什么list是空的？
`[2024-06-05 14:03:31,054: INFO/MainProcess] Task tasks.send_ticket_notice[61f9d016-7654-4863-a8d3-62e9a7f09b0b] received
[2024-06-05 14:03:31,245: INFO/MainProcess] Task tasks.send_ticket_notice[61f9d016-7654-4863-a8d3-62e9a7f09b0b] succeeded in 0.18799999996554106s: (True, {'send_notice_result_list': [{...}]})
`

**Comment by blackholll** [comment]
应该只是celery没打印出来。你在hook服务端加日志调试下

**Comment by blackholll** [comment]
是要获取hook_email 的response？  你这里看起来是吧这个api直接添加到loonflow了 不建议这么做。 建议是单独写个服务。  你的hook服务认为已经成功发送通知的话 就可以return 状态200的json，其中code=0， loonflow就会认为通知成功了，celery日志中也会记录成功的结果。  另外你的hook服务也可以持久化 每次通知的执行情况

**Comment by wtxhai** [comment]
> 是要获取hook_email 的response？ 你这里看起来是吧这个api直接添加到loonflow了 不建议这么做。 建议是单独写个服务。 你的hook服务认为已经成功发送通知的话 就可以return 状态200的json，其中code=0， loonflow就会认为通知成功了，celery日志中也会记录成功的结果。 另外你的hook服务也可以持久化 每次通知的执行情况

你的意思的把hook 这一部分单独创建个项目，让后运行起来吗？

**Comment by wtxhai** [comment]
单独写出来的，但是调用的时候，我怎么才能看到是否执行了这个API
![image](https://github.com/blackholll/loonflow/assets/49899065/2268cea2-d324-420f-aa66-b415083c4fcf)
`import json

from django.utils.decorators import method_decorator
from django.views import View
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

from service.common.common_service import CommonService
from service.hook.hook_participant_service import HookParticipantService, HookNoticeService


@method_decorator(csrf_exempt, name='dispatch')
class HookParticipantView(View):
    def post(self, request, *args, **kwargs):
        json_str = request.body.decode('utf-8')
        signature = request.META.get('HTTP_SIGNATURE', '')
        timestamp = request.META.get('HTTP_TIMESTAMP', '')
        request_data_dict = json.loads(json_str)

        # 校验请求是否合法
        flag, msg = CommonService.check_signature(timestamp, signature)
        if flag:
            flag, msg = HookParticipantService.response_hook_sync(request_data_dict)
            if flag:
                return JsonResponse(dict(code=-1, msg=msg, data=""))
        return JsonResponse(dict(code=0, msg="任务执行成功", data=""))

@method_decorator(csrf_exempt, name='dispatch')
class HookNoticeView(View):
    def post(self, request, *args, **kwargs):
        json_str = request.body.decode('utf-8')
        signature = request.META.get('HTTP_SIGNATURE', '')
        timestamp = request.META.get('HTTP_TIMESTAMP', '')
        request_data_dict = json.loads(json_str)
        # 校验请求是否合法
        flag, msg = CommonService.check_signature(timestamp, signature)
        if flag:
            flag, msg = HookNoticeService.response_notice(request_data_dict)`

**Comment by wtxhai** [comment]
写了个日志打印，流程都完了，都没有跑出来日志，请教一下哪里出问题了
`@method_decorator(csrf_exempt, name='dispatch')
class HookNoticeView(View):
    def post(self, request, *args, **kwargs):
        json_str = request.body.decode('utf-8')
        signature = request.META.get('HTTP_SIGNATURE', '')
        timestamp = request.META.get('HTTP_TIMESTAMP', '')
        request_data_dict = json.loads(json_str)

        # 记录请求数据
        logger.info("Received POST request with data: %s", request_data_dict)

        # 校验请求是否合法
        flag, msg = CommonService.check_signature(timestamp, signature)
        if flag:
            flag, msg = HookNoticeService.response_notice(request_data_dict)

        # 记录处理结果
        logger.info("Response: flag=%s, message=%s", flag, msg)

        return HttpResponse(status=200)  # 根据需要返回适当的响应
`

**Comment by wtxhai** [comment]
![image](https://github.com/blackholll/loonflow/assets/49899065/3f215d62-71e6-4f5f-b2f4-ef859ce6050b)

**Comment by wtxhai** [comment]
> 写了个日志打印，流程都完了，都没有跑出来日志，请教一下哪里出问题了 `@method_decorator(csrf_exempt, name='dispatch') class HookNoticeView(View): def post(self, request, *args, **kwargs): json_str = request.body.decode('utf-8') signature = request.META.get('HTTP_SIGNATURE', '') timestamp = request.META.get('HTTP_TIMESTAMP', '') request_data_dict = json.loads(json_str)
> 
> ```
>     # 记录请求数据
>     logger.info("Received POST request with data: %s", request_data_dict)
> 
>     # 校验请求是否合法
>     flag, msg = CommonService.check_signature(timestamp, signature)
>     if flag:
>         flag, msg = HookNoticeService.response_notice(request_data_dict)
> 
>     # 记录处理结果
>     logger.info("Response: flag=%s, message=%s", flag, msg)
> 
>     return HttpResponse(status=200)  # 根据需要返回适当的响应
> ```
> 
> `

![image](https://github.com/blackholll/loonflow/assets/49899065/081babec-a15e-4520-a83f-7db0555b9ce1)

**Comment by wtxhai** [comment]
写了个日志打印，流程都完了，都没有跑出来日志，请教一下哪里出问题了
![image](https://github.com/blackholll/loonflow/assets/49899065/34c305f2-e971-42b7-8113-1892fe238416)

**Comment by blackholll** [comment]
用logger打日志 需要一些配置 自己搜索下吧。  简单点你可以直接print

**Comment by wtxhai** [comment]
我DEBUG了一下，发现程序没有跑进去，是哪里出问题了？
![image](https://github.com/blackholll/loonflow/assets/49899065/dc8f0aba-28e2-4c36-9f55-3b3920a32b4f)

**Comment by wtxhai** [comment]
上面的问题可以给点思路吗

**Comment by blackholll** [comment]
先loonflow有没有触发。 可以从celery task 的日志里面看出
如果有触发 检查下是否启动了多个hook服务。
检查下是否hook地址配置的有问题

**Comment by wtxhai** [comment]
打印了一下Celery的日志，这个错误是哪里出问题了？
[2024-06-12 11:40:32,657: INFO/MainProcess] celery@NLPM269 ready.
[2024-06-12 11:41:30,444: INFO/MainProcess] Task tasks.send_ticket_notice[6816fe80-1663-4e39-82cd-675f7b919e5c] received
[2024-06-12 11:41:30,677: WARNING/MainProcess] {'notice_id': 7, 'result': 'fail', 'msg': 'permission check fail：appname is not provide in request header'}
[2024-06-12 11:41:30,687: INFO/MainProcess] Task tasks.send_ticket_notice[6816fe80-1663-4e39-82cd-675f7b919e5c] succeeded in 0.23399999999855936s: (True, {'send_notice_result_list': [{...}]})

**Comment by blackholll** [comment]
你是不是把hook服务写到loonflow了？ loonflow对所有api调用有个权限验证。 校验逻辑见https://loonflow.readthedocs.io/zh-cn/r2.0.18/api_docs/authentication/。 

建议单独一个服务， 按照demo里面的实现hook请求的校验逻辑

**Comment by wtxhai** [comment]
你的意思是把hook从apps下面的路径下单独取出来吗？
![image](https://github.com/blackholll/loonflow/assets/49899065/c413b7f1-368b-4e37-9acc-a886097a2eb9)

**Comment by blackholll** [comment]
你现在是把loonflow代码拿来，在loonflow的基础上添加其他功能。 一般不建议这么用。  建议是loonflow作为单独一个工程，你的其他功能另外起一个工程。  
如果你一定要把hook服务放到loonflow来，那就在这里加个例外的逻辑 直接return, 跳过api调用的校验逻辑
https://github.com/blackholll/loonflow/blob/r2.0.18/service/permission/api_permission.py#L20

**Comment by wtxhai** [comment]
> 你现在是把loonflow代码拿来，在loonflow的基础上添加其他功能。 一般不建议这么用。 建议是loonflow作为单独一个工程，你的其他功能另外起一个工程。 如果你一定要把hook服务放到loonflow来，那就在这里加个例外的逻辑 直接return, 跳过api调用的校验逻辑 https://github.com/blackholll/loonflow/blob/r2.0.18/service/permission/api_permission.py#L20

你的意思是到时候我的启用两个工程，一个loonflow工程，一个hook的工程？这样的话是不是有点麻烦，可以集成到一下吗？

**Comment by blackholll** [comment]
我不是说了么。   你如果一定要放在一起就改https://github.com/blackholll/loonflow/blob/r2.0.18/service/permission/api_permission.py#L20  说的还不够清楚么

**Comment by blackholll** [comment]
这是你的hook服务报错的，加些日志或者断点调试下

**Comment by wtxhai** [comment]
V2.0.19版本中，需要传入md5_key的值，我看demo中没有写，这个值我怎么传进去，不传的话会报错。
False
CommonService.signature_check() missing 1 required positional argument: 'md5_key'
![image](https://github.com/blackholll/loonflow/assets/49899065/5a993b8b-7238-485f-af54-78e1d917ea74)
![image](https://github.com/blackholll/loonflow/assets/49899065/ecd140e3-9ce1-4973-96a0-b91de3bf08d0)

**Comment by blackholll** [comment]
这个就是配置hook的时候用的token，  配置的时候用的token是什么， 这里就传什么

**Comment by wtxhai** [comment]
请教一下，我在此处怎么获取我前段配置的token值，前端配置的token是11
![image](https://github.com/blackholll/loonflow/assets/49899065/511eb854-89fb-4c29-b8ad-fafda83166ad)

**Comment by blackholll** [comment]
你在配置通知的时候 配置的是11.   这里直接写死为“11”.  你可以把这个token理解为对称加密的秘钥。 hook发起方的秘钥  和 hook服务的接收方各自保存这个相同的token

**Comment by wtxhai** [comment]
> Owner

明白了，很通透

**Comment by blackholll** [comment]
这里有个错误, 改成  HookNoticeService().response_notice(request_data_dict)

**Comment by wtxhai** [comment]
```python
from email.mime.text import MIMEText
from email.header import Header
import smtplib
from email.mime.multipart import MIMEMultipart

class HookNoticeService:
    def response_notice(self, request_data):
        """
        通知hook
        :param request_data:
        :return:
        """
        participant_info_list = request_data.get('participant_info_list')
        email_list = [participant_info.get('email_list') for participant_info in participant_info_list]
        
        title_result = request_data.get('title_result')  # 工作流标题
        content_result = request_data.get('content_result')  # 通知内容
        
        sender_email = 'xxxxxx.@xxx.com'  # 应替换为实际发件人邮箱地址
        sender_password = 'xxxx'  # 应替换为实际发件人邮箱密码
        smtp_host = 'smtp.example.com'  # 应替换为实际SMTP服务器地址
        smtp_port = 587  # 或者是465，根据SMTP服务器配置
        
        self.send_email(email_list, sender_email, sender_password, smtp_host, smtp_port, title_result, content_result)

    @staticmethod
    def send_email(email_list, sender_email, sender_password, smtp_host, smtp_port, title, content):
        message = MIMEMultipart()
        message['From'] = Header(sender_email)
        message['To'] = Header(','.join(email_list))
        message['Subject'] = Header(title, 'utf-8')

        message.attach(MIMEText(content, 'plain', 'utf-8'))

        try:
            smtpObj = smtplib.SMTP(smtp_host, smtp_port)
            smtpObj.starttls()
            smtpObj.login(sender_email, sender_password)
            smtpObj.sendmail(sender_email, email_list, message.as_string())
            smtpObj.quit()
            print("邮件发送成功")
        except smtplib.SMTPException as e:
            print("Error: 无法发送邮件,", e)
```
大佬执行进去了，邮件也成功发送了，但是执行完上面的代码返回到下面的标记处有报错了，请教一下是哪里出问题了？
![image](https://github.com/blackholll/loonflow/assets/49899065/105a647e-5ce3-40b6-ba0c-6b9d2dfb7884)

**Comment by wtxhai** [comment]
问题圆满结束！功能已实现！感谢大佬期间的耐心解答！
